### ISSUE TITLE
Search does not work after return to search results from a selcted title

### ISSUE THREAD

**Issue by efmmoncada** [Nyumat/NyumatFlix#20]
The search functionality no longer works after selecting a title and returning to the search results via the browsers back button. 

Repro:
1. search for a title
2. select any title
3. use browser back button
4. subsequent searches are no longer executed/ran and results do not update

Experienced on Safari 17.3 (19617.2.4.11.8) and Firefox 121.0.1 (64-bit)

**Comment by Nyumat** [comment]
Thx! Taking a look
